log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  traefik:
    address: ":8123"
  web-secure:
    address: ":443"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          permanent: true

certificatesResolvers:
  myresolver:
    acme:
      email: admin@example.com
      storage: acme.json
      certificatesDuration: 72
      tlsChallenge: {}

accessLog: {}
errorLog: {}

providers:
  file:
    directory: /configuration
    watch: true
